name: FastAPI CI

on:
  push:
    branches: [ main, master, QA ]
  pull_request:
    branches: [ main, master, QA ]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: MONGODB_URI # <-- NOMBRE DEL ENTORNO QUE CREASTE EN GITHUB

    steps:
    - name: Copiar repositorio
      uses: actions/checkout@v6

    - name: Configurar Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Ejecutar pruebas unitarias
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
      run: |
        python -m pytest